function [surfacePosition,x,y] = yOCTFindTissueSurface(varargin)
% This function processes OCT scan data to identify tissue surface from the
% OCT image.
% USAGE:
%   surfacePosition = yOCTFindTissueSurface(meanAbs, dimensions [, outputUnits, isVisualize])
% INPUTS:
%   logMeanAbs, dimensions - data structures generated by yOCTProcessScan.
%       Converted to log scale
%   isVisualize - set to true to generate image heatmap visualization
%       figure. Default is false
% OUTPUTS:
%   - surfacePosition- 2D matrix. dimensions are (y,x). What
%       height is image surface (measured from the top of the OCT scan).
%       physical dimensions of surfacePosition are the same as dimensions.z.units
%   - x,y are the x,y positions that corresponds to surfacePosition(y,x).
%       Units are the same as dimensions.x.units

%% Parse inputs
p = inputParser;
addRequired(p,'logMeanAbs');
addRequired(p,'dimensions');
addParameter(p,'isVisualize',false)

parse(p,varargin{:});
in = p.Results;
logMeanAbs = in.logMeanAbs;
dim = in.dimensions;
isVisualize = in.isVisualize;

%% Do the work

% Tbd, this is just a demo
surfacePosition = ones(size(logMeanAbs,3),size(logMeanAbs,2))*dim.z.values(500);
x=dim.x.values(:);
y=dim.y.values(:);
